name: Check SIMDe headers and update clib.json

on:
  schedule:
    - cron: "15 2 * * *" # Runs nightly
  workflow_dispatch: # Allows manual triggering

jobs:
  update-clib-json:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Checkout the clib repository
        uses: actions/checkout@v4

      - name: Clone SIMDe headers
        run: |
          git clone --depth 1 https://github.com/goodcleanfun/simde_headers.git simde_headers

      - name: Clone the SIMDe repository
        run: |
          git clone --depth 1 https://github.com/simd-everywhere/simde-no-tests.git simde-repo

      - name: Generate list of .h files
        id: generate_files
        run: |
          FILE_LIST=$(python3 simde_headers/simde_headers.py simde-repo x86/avx2.h | sort | tr '\n' ' ' | sed 's/[ ]+$//g')
          echo "::set-output name=file_list::$FILE_LIST"
    
      - name: Copy header files
        run: |
          python3 simde_headers/simde_rewrite_includes.py simde_avx2 simde-repo $(echo "${{ steps.generate_files.outputs.file_list }}") --out-dir=.

      - name: Update clib.json
        run: |
          FILES_CSV=$(echo "${{ steps.generate_files.outputs.file_list }}" | sed -E 's/[^ ]+\///g' | sed -E 's/[[:space:]]/","/g')
          jq ".src = [\"$FILES_CSV\"]" clib.json > clib.json.tmp
          mv clib.json.tmp clib.json

      - name: Check for changes
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          if [ "$(git diff --name-only HEAD)" ]; then
            timestamp=$(date -u)
            git commit -a -m "Update clib.json with latest SIMDe headers [${timestamp}]" || exit 0
            git push
          else
            echo "No changes to commit."
          fi
